spring.application.name=BootMVCProj-14-LOB-uploadingPicsNDdocs

#database config
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/practice_session
spring.datasource.username=root
spring.datasource.password=@Sai0408

#orm config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
